model:
  name: "spatiotemporal"

data: 
  name: "echonet"
  input_key: "video"
  target_key: "batch"

training:
  epochs: 100
  lr: 1.2e-4
  batch_size: 8
  train_batch_size: 64
  val_batch_size: 64
  num_workers: 12
  persistent_workers: true
  weight_decay: 5.0e-5
  patience: 10
  seed: 42
  find_unused_parameters: true
  save_dir: "/workspace/runs"
  checkpoint_dir: "/workspace/checkpoints"
  resume_path: null
  pretrain: false

loss:
  types: ["SpatiotemporalLoss"]
  kwargs:
    dice_weight: 1.0
    flow_weight: 0.5
    curvature_weight: 1.0
    volume_weight: 0.5
    ef_weight: 1.0
wandb:
  enable: true
